### ISSUE TITLE
Upstream podman's Apple Silicon support status

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/podman#5]
#### For main branch
- [x] Re-enable macOS
  - [x] (not disabled in the first place)
- [x] https://github.com/simnalamburt/podman/issues/4
  - [x] https://github.com/containers/common/pull/754
  - [x] https://github.com/containers/podman/pull/11552
- [x] `gvproxy` location https://github.com/simnalamburt/podman/commit/38dcd6eda5f7f89eabbe5a65ad205853c99b604a
  - [x] https://github.com/containers/common/pull/758
  - [x] https://github.com/containers/podman/pull/11552
  - [x] https://github.com/containers/podman/pull/11449
- [x] `edk2-aarch64-code.fd` location https://github.com/simnalamburt/podman/commit/a68a46fed65ec66aa4478b2a620a01967ce1228b
  - [x] https://github.com/containers/podman/pull/11453
  
#### For v3.3 branch
NOTE: v3.3.2 won't be needed if v3.4.0 is released first.
- [ ] Re-enable macOS
- [ ] https://github.com/simnalamburt/podman/issues/4
  - [x] https://github.com/containers/common/pull/754
  - [ ] Use containers/common v0.44.0
- [x] `gvproxy` location https://github.com/simnalamburt/podman/commit/38dcd6eda5f7f89eabbe5a65ad205853c99b604a
  - [x] https://github.com/containers/podman/pull/11234
- [ ] `edk2-aarch64-code.fd` location https://github.com/simnalamburt/podman/commit/a68a46fed65ec66aa4478b2a620a01967ce1228b

**Comment by clarkezone** [comment]
Out of interest, is this fork still needed for M1 mac support in podman?

**Comment by simnalamburt** [comment]
No everything needed has been merged into upstream.

2022년 1월 23일 (일) 03:06, James Clarke ***@***.***>님이 작성:
